version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=magezon.m2.extensions.localhost
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80

  fpm:
    image: meanbee/magento2-php:7.3-fpm
    ports:
      - 9000
    
  cli:
    image: meanbee/magento2-php:7.3-cli
    volumes:
      - ../../../data/composer/cache:/root/.composer/cache

  cron:
    image: meanbee/magento2-php:7.3-cli
    command: run-cron

  db:
    image: mariadb:10.2
    ports:
      - 3306

  elasticsearch:
    build: elasticsearch
    ports:
    - 9200
  
  kibana:
    image: kibana:6.5.4
    ports:
      - 5601

  redis:
    image: 'redis:3.0'
    ports:
      - 6379

  codeception:
    build: codeception
    #volumes:
      #- ../../src/test/e2e:/tests

  appdata:
    image: tianon/true

  dbdata:
    image: tianon/true